apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: kafka-test-apps-producer-sasl
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: kafka-test-apps
      operation: Write
    - resource:
        type: topic
        name: kafka-test-apps
      operation: Create
    - resource:
        type: topic
        name: kafka-test-apps
      operation: Describe
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: kafka-test-apps-consumer-sasl
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: kafka-test-apps
      operation: Read
    - resource:
        type: topic
        name: kafka-test-apps
      operation: Describe
    - resource:
        type: group
        name: my-kafka-consumer-sasl
      operation: Read
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: kafka-test-apps
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
      retention.bytes: 1073741824
      retention.ms: 86400000
      segment.bytes: 1073741824
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-producer-sasl
  name: kafka-producer-sasl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-producer-sasl
    spec:
      containers:
      - name: kafka-producer
        image: scholzj/kafka-producer:latest
        env:
          - name: CA_CRT
            valueFrom:
              secretKeyRef:
                name: my-cluster-cluster-ca-cert
                key: ca.crt
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9093
          - name: TOPIC
            value: kafka-test-apps
          - name: TIMER
            value: "1000"
          - name: NUMBER_OF_KEYS
            value: "3"
          - name: USERNAME
            value: "kafka-test-apps-producer-sasl"
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: kafka-test-apps-producer-sasl
                key: password
#          - name: MESSAGE_COUNT
#            value: "1000000"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer-sasl
  name: kafka-consumer-sasl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-consumer-sasl
    spec:
      containers:
      - name: kafka-consumer
        image: scholzj/kafka-consumer:latest
        env:
          - name: CA_CRT
            valueFrom:
              secretKeyRef:
                name: my-cluster-cluster-ca-cert
                key: ca.crt
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9093
          - name: TOPIC
            value: kafka-test-apps
          - name: GROUP_ID
            value: my-kafka-consumer-sasl
          - name: USERNAME
            value: "kafka-test-apps-consumer-sasl"
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: kafka-test-apps-consumer-sasl
                key: password
#          - name: MESSAGE_COUNT
#            value: "1000000"
